# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'worksite',
                'ordering': ('created_at',),
            },
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
    ]
