# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssapi', '0002_auto_20170128_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_url', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssapi.Worksite')),
            ],
            options={
                'db_table': 'device',
                'ordering': ('created_at',),
            },
        ),
    ]
