# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdsenseapi', '0004_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksite',
            name='descripton',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='device',
            name='reading_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worksite',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worksite',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worksite',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worksite',
            name='zip_code',
            field=models.CharField(max_length=100),
        ),
    ]
