# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdsenseapi', '0006_auto_20170217_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cmdsenseapi.Area'),
        ),
    ]
